"""
The COUNTRY_NAMES const is a hash of alpha-3 country codes containing lists
of country names and aliases.
"""

COUNTRY_NAMES = {
    'ABW': ["aruba"],
    'AFG': ["afghanistan"],
    'AGO': ["angola"],
    'AIA': ["anguilla"],
    'ALA': ["aland islands"],
    'ALB': ["albania"],
    'AND': ["andorra"],
    'ARE': ["united arab emirates"],
    'ARG': ["argentina"],
    'ARM': ["armenia"],
    'ASM': ["american samoa"],
    'ATA': ["antarctica"],
    'ATF': ["french southern territories"],
    'ATG': ["antigua and barbuda"],
    'AUS': ["australia"],
    'AUT': ["austria"],
    'AZE': ["azerbaijan"],
    'BDI': ["burundi"],
    'BEL': ["belgium"],
    'BEN': ["benin"],
    'BES': ["sint eustatius and saba bonaire"],
    'BFA': ["burkina faso"],
    'BGD': ["bangladesh"],
    'BGR': ["bulgaria"],
    'BHR': ["bahrain"],
    'BHS': ["bahamas"],
    'BIH': ["bosnia and herzegovina"],
    'BLM': ["saint barthelemy"],
    'BLR': ["belarus"],
    'BLZ': ["belize"],
    'BMU': ["bermuda"],
    'BOL': ["plurinational state of bolivia"],
    'BRA': ["brazil"],
    'BRB': ["barbados"],
    'BRN': ["brunei darussalam"],
    'BTN': ["bhutan"],
    'BVT': ["bouvet island"],
    'BWA': ["botswana"],
    'CAF': ["central african republic"],
    'CAN': ["canada"],
    'CCK': ["cocos (keeling) islands"],
    'CHE': ["switzerland"],
    'CHL': ["chile"],
    'CHN': ["china"],
    'CIV': ["cote d'ivoire"],
    'CMR': ["cameroon"],
    'COD': ["democratic republic of the congo"],
    'COG': ["congo"],
    'COK': ["cook islands"],
    'COL': ["colombia"],
    'COM': ["comoros"],
    'CPV': ["cabo verde"],
    'CRI': ["costa rica"],
    'CUB': ["cuba"],
    'CUW': ["curacao"],
    'CXR': ["christmas island"],
    'CYM': ["cayman islands"],
    'CYP': ["cyprus"],
    'CZE': ["czech republic"],
    'DEU': ["germany"],
    'DJI': ["djibouti"],
    'DMA': ["dominica"],
    'DNK': ["denmark"],
    'DOM': ["dominican republic"],
    'DZA': ["algeria"],
    'ECU': ["ecuador"],
    'EGY': ["egypt"],
    'ERI': ["eritrea"],
    'ESH': ["western sahara"],
    'ESP': ["spain"],
    'EST': ["estonia"],
    'ETH': ["ethiopia"],
    'FIN': ["finland"],
    'FJI': ["fiji"],
    'FLK': ["falkland islands (malvinas)"],
    'FRA': ["france"],
    'FRO': ["faroe islands"],
    'FSM': ["federated states of micronesia"],
    'GAB': ["gabon"],
    'GBR': ["united kingdom"],
    'GEO': ["georgia"],
    'GGY': ["guernsey"],
    'GHA': ["ghana"],
    'GIB': ["gibraltar"],
    'GIN': ["guinea"],
    'GLP': ["guadeloupe"],
    'GMB': ["gambia"],
    'GNB': ["guinea-bissau"],
    'GNQ': ["equatorial guinea"],
    'GRC': ["greece"],
    'GRD': ["grenada"],
    'GRL': ["greenland"],
    'GTM': ["guatemala"],
    'GUF': ["french guiana"],
    'GUM': ["guam"],
    'GUY': ["guyana"],
    'HKG': ["hong kong"],
    'HMD': ["heard island and mcdonald islands"],
    'HND': ["honduras"],
    'HRV': ["croatia"],
    'HTI': ["haiti"],
    'HUN': ["hungary"],
    'IDN': ["indonesia"],
    'IMN': ["isle of man"],
    'IND': ["india"],
    'IOT': ["british indian ocean territory"],
    'IRL': ["ireland"],
    'IRN': ["islamic republic of iran"],
    'IRQ': ["iraq"],
    'ISL': ["iceland"],
    'ISR': ["israel"],
    'ITA': ["italy"],
    'JAM': ["jamaica"],
    'JEY': ["jersey"],
    'JOR': ["jordan"],
    'JPN': ["japan"],
    'KAZ': ["kazakhstan"],
    'KEN': ["kenya"],
    'KGZ': ["kyrgyzstan"],
    'KHM': ["cambodia"],
    'KIR': ["kiribati"],
    'KNA': ["saint kitts and nevis"],
    'KOR': ["republic of korea"],
    'KWT': ["kuwait"],
    'LAO': ["lao people's democratic republic"],
    'LBN': ["lebanon"],
    'LBR': ["liberia"],
    'LBY': ["libya"],
    'LCA': ["saint lucia"],
    'LIE': ["liechtenstein"],
    'LKA': ["sri lanka"],
    'LSO': ["lesotho"],
    'LTU': ["lithuania"],
    'LUX': ["luxembourg"],
    'LVA': ["latvia"],
    'MAC': ["macao"],
    'MAF': ["saint martin (french part)"],
    'MAR': ["morocco"],
    'MCO': ["monaco"],
    'MDA': ["republic of moldova"],
    'MDG': ["madagascar"],
    'MDV': ["maldives"],
    'MEX': ["mexico"],
    'MHL': ["marshall islands"],
    'MKD': ["the former yugoslav republic of macedonia"],
    'MLI': ["mali"],
    'MLT': ["malta"],
    'MMR': ["myanmar"],
    'MNE': ["montenegro"],
    'MNG': ["mongolia"],
    'MNP': ["northern mariana islands"],
    'MOZ': ["mozambique"],
    'MRT': ["mauritania"],
    'MSR': ["montserrat"],
    'MTQ': ["martinique"],
    'MUS': ["mauritius"],
    'MWI': ["malawi"],
    'MYS': ["malaysia"],
    'MYT': ["mayotte"],
    'NAM': ["namibia"],
    'NCL': ["new caledonia"],
    'NER': ["niger"],
    'NFK': ["norfolk island"],
    'NGA': ["nigeria"],
    'NIC': ["nicaragua"],
    'NIU': ["niue"],
    'NLD': ["netherlands"],
    'NOR': ["norway"],
    'NPL': ["nepal"],
    'NRU': ["nauru"],
    'NZL': ["new zealand"],
    'OMN': ["oman"],
    'PAK': ["pakistan"],
    'PAN': ["panama"],
    'PCN': ["pitcairn"],
    'PER': ["peru"],
    'PHL': ["philippines"],
    'PLW': ["palau"],
    'PNG': ["papua new guinea"],
    'POL': ["poland"],
    'PRI': ["puerto rico"],
    'PRK': ["democratic people's republic of korea"],
    'PRT': ["portugal"],
    'PRY': ["paraguay"],
    'PSE': ["state of palestine"],
    'PYF': ["french polynesia"],
    'QAT': ["qatar"],
    'REU': ["reunion"],
    'ROU': ["romania"],
    'RUS': ["russian federation", "russia"],
    'RWA': ["rwanda"],
    'SAU': ["saudi arabia"],
    'SDN': ["sudan"],
    'SEN': ["senegal"],
    'SGP': ["singapore"],
    'SGS': ["south georgia and the south sandwich islands"],
    'SHN': ["ascension and tristan da cunha saint helena"],
    'SJM': ["svalbard and jan mayen"],
    'SLB': ["solomon islands"],
    'SLE': ["sierra leone"],
    'SLV': ["el salvador"],
    'SMR': ["san marino"],
    'SOM': ["somalia"],
    'SPM': ["saint pierre and miquelon"],
    'SRB': ["serbia"],
    'SSD': ["south sudan"],
    'STP': ["sao tome and principe"],
    'SUR': ["suriname"],
    'SVK': ["slovakia"],
    'SVN': ["slovenia"],
    'SWE': ["sweden"],
    'SWZ': ["swaziland"],
    'SXM': ["sint maarten (dutch part)"],
    'SYC': ["seychelles"],
    'SYR': ["syrian arab republic"],
    'TCA': ["turks and caicos islands"],
    'TCD': ["chad"],
    'TGO': ["togo"],
    'THA': ["thailand"],
    'TJK': ["tajikistan"],
    'TKL': ["tokelau"],
    'TKM': ["turkmenistan"],
    'TLS': ["timor-leste"],
    'TON': ["tonga"],
    'TTO': ["trinidad and tobago"],
    'TUN': ["tunisia"],
    'TUR': ["turkey"],
    'TUV': ["tuvalu"],
    'TWN': ["province of china taiwan"],
    'TZA': ["united republic of tanzania"],
    'UGA': ["uganda"],
    'UKR': ["ukraine"],
    'UMI': ["united states minor outlying islands"],
    'URY': ["uruguay"],
    'USA': ["united states", "usa", "america"],
    'UZB': ["uzbekistan"],
    'VAT': ["holy see (vatican city state)"],
    'VCT': ["saint vincent and the grenadines"],
    'VEN': ["bolivarian republic of venezuela"],
    'VGB': ["british virgin islands"],
    'VIR': ["u.s. virgin islands"],
    'VNM': ["viet nam"],
    'VUT': ["vanuatu"],
    'WLF': ["wallis and futuna"],
    'WSM': ["samoa"],
    'YEM': ["yemen"],
    'ZAF': ["south africa"],
    'ZMB': ["zambia"],
    'ZWE': ["zimbabwe"]
}
