"""
The COUNTRY_NAMES const is a hash of alpha-3 country codes containing lists
of country names and aliases.
"""

COUNTRY_NAMES = {
    'ABW': ["aruba"],
    'AFG': ["afghanistan"],
    'AGO': ["angola"],
    'AIA': ["anguilla"],
    'ALA': ["aland islands"],
    'ALB': ["albania"],
    'AND': ["andorra"],
    'ARE': ["united arab emirates", " uae", "emirati", "dubai"],
    'ARG': ["argentina"],
    'ARM': ["armenia"],
    'ASM': ["american samoa"],
    'ATA': ["antarctica", "south pole"],
    'ATF': ["french southern territories"],
    'ATG': ["antigua and barbuda", "barbuda", "antigua"],
    'AUS': ["australia", "aussie"],
    'AUT': ["austria"],
    'AZE': ["azerbaijan"],
    'BDI': ["burundi"],
    'BEL': ["belgium", "belgian", "flemish"],
    'BEN': ["benin"],
    'BES': [
        "sint eustatius and saba bonaire", "caribbean netherlands", "bonaire",
        "sint eustatius", "saba"],
    'BFA': ["burkina faso", "burkina"],
    'BGD': ["bangladesh"],
    'BGR': ["bulgaria"],
    'BHR': ["bahrain"],
    'BHS': ["bahamas"],
    'BIH': ["bosnia and herzegovina", "bosnia", "herzegovina"],
    'BLM': ["saint barthelemy", "st. barts", "st. barths"],
    'BLR': ["belarus"],
    'BLZ': ["belize"],
    'BMU': ["bermuda"],
    'BOL': ["plurinational state of bolivia", "bolivia"],
    'BRA': ["brazil"],
    'BRB': ["barbados"],
    'BRN': ["brunei darussalam"],
    'BTN': ["bhutan"],
    'BVT': ["bouvet island"],
    'BWA': ["botswana"],
    'CAF': ["central african republic", "centrafrique"],
    'CAN': [
        "canada", "ottawa", "toronto", "montreal", "calgary", "ottawa",
        "alberta", "british columbia", "manitoba", "new brunswick",
        "newfoundland", "nova scotia", "ontario", "prince edward island",
        "quebec", "saskatchewan"],
    'CCK': ["cocos (keeling) islands", "cocos islands", "keeling islands"],
    'CHE': ["switzerland", "swiss"],
    'CHL': ["chile"],
    'CHN': [
        "china", "beijing", "chinese", "beijing", "peking", "shanghai",
        "hong kong"],
    'CIV': ["cote d'ivoire", "ivory coast"],
    'CMR': ["cameroon"],
    'COD': ["democratic republic of the congo", "congo"],
    'COG': ["congo"],
    'COK': ["cook islands"],
    'COL': ["colombia"],
    'COM': ["comoros"],
    'CPV': ["cabo verde", "cape verde"],
    'CRI': ["costa rica"],
    'CUB': ["cuba", "castro"],
    'CUW': ["curacao"],
    'CXR': ["christmas island"],
    'CYM': ["cayman islands", "cayman"],
    'CYP': ["cyprus"],
    'CZE': ["czech republic", "czech"],
    'DEU': ["germany", "german"],
    'DJI': ["djibouti"],
    'DMA': ["dominica"],
    'DNK': ["denmark"],
    'DOM': ["dominican republic", "dominican"],
    'DZA': ["algeria", "algerie" "algiers"],
    'ECU': ["ecuador"],
    'EGY': ["egypt"],
    'ERI': ["eritrea"],
    'ESH': ["western sahara"],
    'ESP': ["spain", "spanish"],
    'EST': ["estonia"],
    'ETH': ["ethiopia"],
    'FIN': ["finland", "finnish", "finn"],
    'FJI': ["fiji"],
    'FLK': ["falkland islands (malvinas)", "falkland", "malvinas"],
    'FRA': ["france", "french", "paris"],
    'FRO': ["faroe islands"],
    'FSM': ["federated states of micronesia", "Micronesia"],
    'GAB': ["gabon"],
    'GBR': [
        "united kingdom", "england", "london", "u.k.", "britain",
        "great britain", "northern ireland", "scotland", "wales"],
    'GEO': ["georgia"],
    'GGY': ["guernsey"],
    'GHA': ["ghana"],
    'GIB': ["gibraltar"],
    'GIN': ["guinea"],
    'GLP': ["guadeloupe"],
    'GMB': ["gambia"],
    'GNB': ["guinea-bissau"],
    'GNQ': ["equatorial guinea"],
    'GRC': ["greece"],
    'GRD': ["grenada"],
    'GRL': ["greenland"],
    'GTM': ["guatemala"],
    'GUF': ["french guiana"],
    'GUM': ["guam"],
    'GUY': ["guyana"],
    'HKG': ["hong kong"],
    'HMD': [
        "heard island and mcdonald islands", "heard island",
        "mcdonald islands"],
    'HND': ["honduras"],
    'HRV': ["croatia"],
    'HTI': ["haiti"],
    'HUN': ["hungary"],
    'IDN': ["indonesia"],
    'IMN': ["isle of man"],
    'IND': ["india"],
    'IOT': ["british indian ocean territory", "Chagos Islands", "Chagos"],
    'IRL': ["ireland"],
    'IRN': ["islamic republic of iran", "iran"],
    'IRQ': ["iraq", "baghdad"],
    'ISL': ["iceland"],
    'ISR': ["israel"],
    'ITA': ["italy"],
    'JAM': ["jamaica"],
    'JEY': ["jersey"],
    'JOR': ["jordan"],
    'JPN': ["japan"],
    'KAZ': ["kazakhstan"],
    'KEN': ["kenya"],
    'KGZ': ["kyrgyzstan"],
    'KHM': ["cambodia"],
    'KIR': ["kiribati"],
    'KNA': [
        "saint kitts and nevis", "saint kitts", "nevis", "saint christopher",
        "saint-christophe"],
    'KOR': ["republic of korea", "south korea", "seoul", "korean"],
    'KWT': ["kuwait"],
    'LAO': ["lao people's democratic republic", "laos"],
    'LBN': ["lebanon"],
    'LBR': ["liberia"],
    'LBY': ["libya"],
    'LCA': ["saint lucia"],
    'LIE': ["liechtenstein"],
    'LKA': ["sri lanka"],
    'LSO': ["lesotho"],
    'LTU': ["lithuania"],
    'LUX': ["luxembourg"],
    'LVA': ["latvia"],
    'MAC': ["macao"],
    'MAF': ["saint martin (french part)", "saint martin"],
    'MAR': ["morocco"],
    'MCO': ["monaco"],
    'MDA': ["republic of moldova", "moldova"],
    'MDG': ["madagascar"],
    'MDV': ["maldives"],
    'MEX': ["mexico", "mexican"],
    'MHL': ["marshall islands"],
    'MKD': ["the former yugoslav republic of macedonia", "macedonia"],
    'MLI': ["mali "],
    'MLT': ["malta"],
    'MMR': ["myanmar"],
    'MNE': ["montenegro"],
    'MNG': ["mongolia"],
    'MNP': ["northern mariana islands"],
    'MOZ': ["mozambique"],
    'MRT': ["mauritania", "maghreb"],
    'MSR': ["montserrat"],
    'MTQ': ["martinique"],
    'MUS': ["mauritius"],
    'MWI': ["malawi"],
    'MYS': ["malaysia"],
    'MYT': ["mayotte"],
    'NAM': ["namibia"],
    'NCL': ["new caledonia"],
    'NER': ["niger"],
    'NFK': ["norfolk island"],
    'NGA': ["nigeria"],
    'NIC': ["nicaragua"],
    'NIU': ["niue"],
    'NLD': ["netherlands", "holland", "dutch", "flemish"],
    'NOR': ["norway", "norwegian", "oslo"],
    'NPL': ["nepal"],
    'NRU': ["nauru"],
    'NZL': ["new zealand"],
    'OMN': ["oman"],
    'PAK': ["pakistan"],
    'PAN': ["panama"],
    'PCN': ["pitcairn"],
    'PER': ["peru"],
    'PHL': ["philippines", "filipino"],
    'PLW': ["palau"],
    'PNG': ["papua new guinea"],
    'POL': ["poland", "polish"],
    'PRI': ["puerto rico", "puerto rican"],
    'PRK': [
        "democratic people's republic of korea", "north korea", "kim jong-un",
        "kim jong un", "pyongyang"],
    'PRT': ["portugal"],
    'PRY': ["paraguay"],
    'PSE': ["state of palestine", "palestine", "gaza", "west bank"],
    'PYF': ["french polynesia"],
    'QAT': ["qatar"],
    'REU': ["reunion"],
    'ROU': ["romania"],
    'RUS': ["russian federation", "russia", "putin", "moscow"],
    'RWA': ["rwanda"],
    'SAU': ["saudi arabia", "saudi"],
    'SDN': ["sudan"],
    'SEN': ["senegal"],
    'SGP': ["singapore"],
    'SGS': [
        "south georgia and the south sandwich islands", "south georgia",
        "south sandwich islands"],
    'SHN': [
        "ascension and tristan da cunha saint helena", "saint helena",
        "ascension island", "tristan da cunha"],
    'SJM': ["svalbard and jan mayen", "svalbard", "jan mayen"],
    'SLB': ["solomon islands"],
    'SLE': ["sierra leone"],
    'SLV': ["el salvador"],
    'SMR': ["san marino"],
    'SOM': ["somalia"],
    'SPM': ["saint pierre and miquelon", "saint pierre", "miquelon"],
    'SRB': ["serbia"],
    'SSD': ["south sudan"],
    'STP': ["sao tome and principe", "sao tome", "principe"],
    'SUR': ["suriname"],
    'SVK': ["slovakia"],
    'SVN': ["slovenia"],
    'SWE': ["sweden", "swedish", "swede"],
    'SWZ': ["swaziland"],
    'SXM': ["sint maarten (dutch part)", "sint maarten"],
    'SYC': ["seychelles"],
    'SYR': ["syrian arab republic", "syria"],
    'TCA': ["turks and caicos islands", "caicos island", "turks island"],
    'TCD': ["chad"],
    'TGO': ["togo"],
    'THA': ["thailand", "thai"],
    'TJK': ["tajikistan"],
    'TKL': ["tokelau"],
    'TKM': ["turkmenistan"],
    'TLS': ["timor-leste", "east timor"],
    'TON': ["tonga"],
    'TTO': ["trinidad and tobago"],
    'TUN': ["tunisia"],
    'TUR': ["turkey"],
    'TUV': ["tuvalu"],
    'TWN': ["province of china taiwan", "taiwan"],
    'TZA': ["united republic of tanzania", "tanzania"],
    'UGA': ["uganda"],
    'UKR': ["ukraine"],
    'UMI': [
        "united states minor outlying islands", "baker island",
        "howland island", "jarvis island", "johnston atoll", "kingman reef",
        "midway islands", "palmyra atoll", "wake island"],
    'URY': ["uruguay"],
    'USA': [
        "united states", "u.s.a.", "america", "obama", "new york", "manhattan",
        "u.s.", "brooklyn", "silicon valley", "nsa", "nasa", "clinton",
        "washington", "usaid", "snowden", "texas", "california", "florida",
        "nyc", "broadway", " usa "],
    'UZB': ["uzbekistan"],
    'VAT': ["holy see (vatican city state)", "vatican", "pope", "catholic"],
    'VCT': ["saint vincent and the grenadines", "saint vincent", "st vincent"],
    'VEN': ["bolivarian republic of venezuela", "venezuela", "caracas"],
    'VGB': [
        "british virgin islands",  "tortola", "virgin gorda", "anegada",
        "jost van dyke"],
    'VIR': ["u.s. virgin islands"],
    'VNM': ["viet nam", "vietnam"],
    'VUT': ["vanuatu"],
    'WLF': ["wallis and futuna", "wallis", "futuna"],
    'WSM': ["samoa"],
    'YEM': ["yemen"],
    'ZAF': ["south africa"],
    'ZMB': ["zambia"],
    'ZWE': ["zimbabwe"]
}

EU = [
    "AUT", "BEL", "BGR", "CYP", "CZE", "DNK", "EST", "FIN", "FRA", "DEU",
    "GRC", "HUN", "IRL", "ITA", "LVA", "LTU", "LUX", "MLT", "NLD", "POL",
    "PRT", "ROU", "SVK", "SVN", "ESP", "SWE", "GBR"]

for country in EU:
    COUNTRY_NAMES[country].extend(["european union", "e.u."])

WEST_AFRICA = [
    "BEN", "BFA", "CPV", "GMB", "GHA", "GIN", "GNB", "CIV", "LBR", "MLI",
    "MRT", "NER", "NGA", "SHN", "SEN", "SLE", "TGO"]

for country in WEST_AFRICA:
    COUNTRY_NAMES[country].extend([
        "western africa", "west africa", "west of africa"])
